# app/infer/labels.py

CLASSES = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

CLASS_KO = {
    "Apple___Apple_scab": "사과 잎 검은별무늬병",
    "Apple___Black_rot": "사과 검은썩음병",
    "Apple___Cedar_apple_rust": "사과 붉은녹병",
    "Apple___healthy": "사과 건강함",
    "Blueberry___healthy": "블루베리 건강함",
    "Cherry_(including_sour)___Powdery_mildew": "체리 흰가루병",
    "Cherry_(including_sour)___healthy": "체리 건강함",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "옥수수 점무늬병",
    "Corn_(maize)___Common_rust_": "옥수수 녹병",
    "Corn_(maize)___Northern_Leaf_Blight": "옥수수 북부잎마름병",
    "Corn_(maize)___healthy": "옥수수 건강함",
    "Grape___Black_rot": "포도 검은썩음병",
    "Grape___Esca_(Black_Measles)": "포도 에스카병(블랙미즐)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "포도 잎마름병",
    "Grape___healthy": "포도 건강함",
    "Orange___Haunglongbing_(Citrus_greening)": "감귤 황화병(HLB)",
    "Peach___Bacterial_spot": "복숭아 세균성반점병",
    "Peach___healthy": "복숭아 건강함",
    "Pepper,_bell___Bacterial_spot": "피망 세균성반점병",
    "Pepper,_bell___healthy": "피망 건강함",
    "Potato___Early_blight": "감자 겹무늬병",
    "Potato___Late_blight": "감자 역병",
    "Potato___healthy": "감자 건강함",
    "Raspberry___healthy": "라즈베리 건강함",
    "Soybean___healthy": "콩 건강함",
    "Squash___Powdery_mildew": "호박 흰가루병",
    "Strawberry___Leaf_scorch": "딸기 잎마름병",
    "Strawberry___healthy": "딸기 건강함",
    "Tomato___Bacterial_spot": "토마토 세균성반점병",
    "Tomato___Early_blight": "토마토 겹무늬병",
    "Tomato___Late_blight": "토마토 역병",
    "Tomato___Leaf_Mold": "토마토 잎곰팡이병",
    "Tomato___Septoria_leaf_spot": "토마토 점무늬병",
    "Tomato___Spider_mites Two-spotted_spider_mite": "토마토 점박이응애 피해",
    "Tomato___Target_Spot": "토마토 표적무늬병",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "토마토 황화잎말림바이러스병",
    "Tomato___Tomato_mosaic_virus": "토마토 모자이크바이러스병",
    "Tomato___healthy": "토마토 건강함",
    "Invalid": "결과 없음",

}

def to_korean(label_en: str) -> str:
    return CLASS_KO.get(label_en, label_en)
