server {
  listen 80;
  server_name _;    # www.matefarm.com 으로 접근하거나, 서버의 IP로 접근하거나 _ (와일드 카드)로 열어두면 서버로 오는 모든 요청을 허용한다.

  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 52M; # 개별 파일 사이즈 제한을 nginx에서 한 번 검사

  # API → backend 서비스로 프록시 (prod compose 네트워크에서 이름: backend)
  location /api/ {
  # Docker Compose의 서비스 이름 사용 | axios.post("/api") 로 사용중이기에 프록시 경로에서 "/"를 제거
    proxy_pass http://backend:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme; # HTTPS 사용을 위해 추가
  }

  # SPA fallback
  location / {
    try_files $uri /index.html;
  }
}