# local 환경에서 사용할 docker-compose 설정파일
version: '3.9'
services:
  db:
    image: mariadb:10.11
    container_name: db
    env_file:
      - .env.local.db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: matefarm
      MYSQL_USER: matefarm
      MYSQL_PASSWORD: matefarm

    ports:
      - "3308:3306"   # 호스트 3308 → 컨테이너 3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      # DB가 살아있는지 확인. ( health Check )
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      # test 명령을 실행했을 때 5초 안에 응답이 없으면 실패로 간주
      timeout: 5s
      retries: 10

  backend:
    build: ../backend/matefarm
    container_name: backend
    env_file:
      - .env.local.back
    environment:
      # yaml 파일 설정.
#      SPRING_PROFILES_ACTIVE: local
      # DB Service name 으로 수정
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/matefarm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME} 괜히 .env에 있는데 따로 설정했다가 변수명 꼬여서 인식 안된다.
    ports:
      - "8080:8080"
      # DB health Check 후 OK 면 backend build.
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ../frontend
    container_name: frontend
    environment: {}
    ports:
      - "80:80"
    depends_on:
      - backend

  # Redis 추가
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dbdata: