services:
  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      - ./services/orchestrator/.env
    environment:
      - LIRIOPE_URL=http://model-liriope:8010/predict
      - WAMBUGU_URL=http://model-wambugu:8020/predict
      - EMBEDDER_BASE_URL=http://embedder:8030
    depends_on:
      - model-liriope
      - model-wambugu
      - embedder

  model-liriope:
    build: ./services/model-liriope
    ports:
      - "8010:8010"
    volumes:
      - ./examples/images:/test-images:ro
      - "D:/hf-cache:/hf"
    environment:
      - HF_HOME=/hf
      - HF_HUB_CACHE=/hf/hub
      - TRANSFORMERS_CACHE=/hf/transformers

  model-wambugu:
    build: ./services/model-wambugu
    ports:
      - "8020:8020"
    volumes:
      - ./examples/images:/test-images:ro
      - "D:/hf-cache:/hf"
    environment:
      - HF_HOME=/hf
      - HF_HUB_CACHE=/hf/hub
      - TRANSFORMERS_CACHE=/hf/transformers

  embedder:
    build: ./services/embedder
    ports: 
      - "8030:8030"
    volumes:
      - ./services/embedder/data/chroma_db:/chroma
    environment:
      - CHROMA_PERSIST_DIR=/chroma
